### ISSUE TITLE
Fix Color of footer and navbar !

### ISSUE THREAD

**Issue by AbhineshJha** [AbhineshJha/Redstore#15]
Fix the red color in footer and navbar by their default color and also add hover !!

**Comment by BuilderPrid** [comment]
Can you assign this to me?

**Comment by liuhuijuan12** [comment]
I want to finish this task. Would you please assign it to me?

**Comment by AbhineshJha** [comment]
this is done by another guy , thanks for your effort , so i am closing this issue
