### ISSUE TITLE
[FEAT] Add hover transition to the products.

### ISSUE THREAD

**Issue by RuthwikReddy09** [AbhineshJha/Redstore#23]
Currently, the hover effect on the products is not smooth.
adding transitions will make the hover effect smoother and will improve the user experience.

[screen-capture (1).webm](https://github.com/AbhineshJha/Redstore/assets/126862059/79256229-a4a6-458a-a21f-b5e3695635ba)

**Comment by RuthwikReddy09** [comment]
I'd like to work on this. Can you assign this issue to me?

**Comment by AbhineshJha** [comment]
done @RuthwikReddy09
