### ISSUE TITLE
Favicon Should be added in all Web Pages !!

### ISSUE THREAD

**Issue by prashh-k** [AbhineshJha/Redstore#49]
In Issue #3 @DeepRahangdale maybe discussed about adding favicon in **Homepage** only, 
But here I want to add favicon in all **web pages** includes Our Product, About us, Contact us.
 
**Expected Behavior:**
The favicon should be added like this in all Web pages,
![fav_redstone_after](https://github.com/AbhineshJha/Redstore/assets/104455228/35aa9385-39a7-4b6c-8bdf-ed3c8a60e68b)

**Actual Behavior:**
The favicon is not added in all web pages ,
![fav_redstone_before](https://github.com/AbhineshJha/Redstore/assets/104455228/0fb666dd-85f9-4cdc-b80d-c8b4b60f2833)

**Comment by prashh-k** [comment]
Thanks you so much kindly please add Hactobarfestt2023 label in issue

**Comment by AbhineshJha** [comment]
done
