### ISSUE TITLE
Responsive navbar

### ISSUE THREAD

**Issue by AbhineshJha** [AbhineshJha/Redstore#5]
Add responsiveness in the navigation bar

**Comment by Asheklm6** [comment]
@AbhineshJha  pls can i work on this

**Comment by ShrujanaReddy** [comment]
Hey ! I would like to work on this. Please assign me this issue.

**Comment by ShrujanaReddy** [comment]
Hey ! Sorry for not being able to complete the work. I'm unassigning myself.

**Comment by code-bajju** [comment]
@AbhineshJha As a professional developer and freelancer i can work on this issue. You can assign me this i will complete within 24 hours . Thank You <3
