### ISSUE TITLE
Responsive Footer 

### ISSUE THREAD

**Issue by AbhineshJha** [AbhineshJha/Redstore#6]
Add responsiveness in footer

**Comment by JureBl** [comment]
Can I work on this?

**Comment by AbhineshJha** [comment]
go for it @JureBl

**Comment by JureBl** [comment]
Hey AbhineshJha. Can you unassign me?  I cant solve this Problem.

**Comment by leabuende** [comment]
Hey @AbhineshJha, can you assign me ? I want to try this out

**Comment by AbhineshJha** [comment]
done @leabuende

**Comment by leabuende** [comment]
Just pushed the fix @AbhineshJha, waiting for your approval and/or feedback ! 🚀
