### ISSUE TITLE
Add account section page in the footer.

### ISSUE THREAD

**Issue by vedansh2001** [AbhineshJha/Redstore#61]
The account section is present in the footer section but its not working.
Please assign it to me.
![Screenshot 2023-10-28 105849](https://github.com/AbhineshJha/Redstore/assets/122162739/03faf7e4-120b-41a1-a5f4-c7fa91f54e5c)

**Comment by Maedamori22** [comment]
The account section is present in the footer section but its not working. What does "not working" mean?

**Comment by vedansh2001** [comment]
I meant that "account" is present in the footer section but it's not clickable ( since the account section code was not written).
You have already merged the pull request of mine which included the code for account. So now its working and this issue can be closed.
